networks: 
  autofe_workflow:
    external: true
services:
  autofe-notebook-dev:
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
      dockerfile: Dockerfile
      context: ./
    command:
      - /bin/bash
      - -c
      - |
        jupyter lab --allow-root --ip 0.0.0.0 --NotebookApp.token='' --NotebookApp.password='' --notebook-dir /home/vmagent/app/
    container_name: autofe_dev
    network_mode: "host"
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
    image: intel/ai-workflows:pa-autofe
    privileged: true
    devices:
      - /dev/dri
    volumes: 
      - ../:/home/vmagent/app/
    working_dir: /home/vmagent/app/
    shm_size: 300g
