general:
  run_ray_cluster: True
  run_hdfs: True
  run_training_job: False
  model_dir: /home/fanlilin/.cache/huggingface # all folders are NFS-shared across nodes 
  tmp_dir: /home/fanlilin/tmp
  workspace_dir: /home/fanlilin/workspace/llm-ray-fanli
  image_name: ray-llm:latest

nodes:
  - node: 10.165.9.53
    type: head
    cores: 0-95

  - node: 10.165.9.51
    type: worker
    cores: 0-95
    user: fanlilin
    password: Intel123

training_spec:
  task_name: clm  
  config_path: ./llm_finetune_template.conf
